# Generated by Django 4.2.5 on 2024-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employed', models.CharField(max_length=255)),
                ('lastname_employed', models.CharField(max_length=200)),
                ('phone_employed', models.CharField(max_length=255)),
                ('sex_employed', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('service_employed', models.CharField(choices=[('HAS', 'Hopital Adolphe Assicé'), ('HDL', 'Hopital de Loandjili'), ('HDTT', 'Hopital de Tié Tié'), ('HDP', 'Hopital de PATRA')], max_length=10)),
                ('date_employed', models.DateField()),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'employés',
            },
        ),
        migrations.CreateModel(
            name='PersonalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_personal', models.CharField(max_length=100)),
                ('lastname_personal', models.CharField(max_length=100)),
                ('sex_personal', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('phone_personal', models.CharField(max_length=50)),
                ('email_personal', models.EmailField(max_length=255)),
                ('date_personal', models.DateField()),
            ],
            options={
                'verbose_name': 'personnel du bureau',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('lastname_user', models.CharField(max_length=100)),
                ('sex_user', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('phone_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=255)),
                ('date_user', models.DateField()),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
    ]
